### PR TITLE
rename h_bankfull to bankfull_depth

### LINKED ISSUE #197: consistent naming of "bankfull_depth" parameter
The same parameter is named "h_bankfull" for kin wave routing. I suggest to change "h_bankfull" to "bankfull_depth".

### PR DESCRIPTION
**Pull request by DirkEilander**
fixes #197

### CODE REVIEW

**Comment by DirkEilander** [comment]
I did not get the tests to run on my machine.. Could the failing tests have to do with a wflow config toml file that need to be updated somewhere?

**Comment by verseve** [comment]
It now uses the actual `riverdepth` map for the kinematic wave, before this change the default value was used. This is causing some small differences.

**Comment by verseve** [comment]
Could you also please update the changelog (this is breaking)? And request a review?

**Review by verseve — APPROVED** [review]
Thanks for solving this issue!

**Pull request merged**
